export const initialInfoState = {
	brand: '',
	model: '',
	street: '',
	city: '',
	email: '',
	mobileNumber: '',
	state: '',
	country: '',
	price: 0,
	zipCode: '',
	licensePlateNumber: '',
	carRegistrationNumber: '',
	carAvailability: { startDate: new Date(), endDate: new Date() },
	vehiclePhotos: [],
};
